package commands;

public enum CommandType {
    FILE_REQUEST,
    FILE_MESSAGE,
    FILE_PART,
    LIST_REQUEST,
    LIST_MESSAGE,
    DELETE_REQUEST,
    RENAME_REQUEST,
    PATH_UP,
    PATH_RESPONSE,
    FOCUS_RESPONSE,
    FOCUS_REQUEST,
    PATH_IN_REQUEST,
    CREATE_DIRECTORY
}
